package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"fmt"

	"github.com/bamdadam/backend/graph/model"
)

// UpdateElementTitle is the resolver for the updateElementTitle field.
func (r *mutationResolver) UpdateElementTitle(ctx context.Context, input model.UpdateElementTitleInput) (*model.Element, error) {
	panic(fmt.Errorf("not implemented: UpdateElementTitle - updateElementTitle"))
}

// Element is the resolver for the element field.
func (r *queryResolver) Element(ctx context.Context, uri string) (*model.Element, error) {
	panic(fmt.Errorf("not implemented: Element - element"))
}

// Elements is the resolver for the elements field.
func (r *queryResolver) Elements(ctx context.Context, first *int32, after *string, last *int32, before *string, typeURI *string, spaceURI *string, fieldValueFilter *model.FieldValueFilter) (*model.ElementConnection, error) {
	panic(fmt.Errorf("not implemented: Elements - elements"))
}

// ElementUpdated is the resolver for the elementUpdated field.
func (r *subscriptionResolver) ElementUpdated(ctx context.Context, uri string) (<-chan *model.Element, error) {
	panic(fmt.Errorf("not implemented: ElementUpdated - elementUpdated"))
}

// ElementCreated is the resolver for the elementCreated field.
func (r *subscriptionResolver) ElementCreated(ctx context.Context) (<-chan *model.Element, error) {
	panic(fmt.Errorf("not implemented: ElementCreated - elementCreated"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
