package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"

	"github.com/bamdadam/backend/graph/model"
	models "github.com/bamdadam/backend/src/model"
)

// UpdateElementTitle is the resolver for the updateElementTitle field.
func (r *mutationResolver) UpdateElementTitle(ctx context.Context, input model.UpdateElementTitleInput) (*model.Element, error) {
	elem, err := r.ElementService.UpdateTitle(ctx, input.URI, input.Title)
	if err != nil {
		return nil, err
	}
	r.ElementPubSub.Publish(elem)
	return elem, nil
}

// Element is the resolver for the element field.
func (r *queryResolver) Element(ctx context.Context, uri string) (*model.Element, error) {
	return r.ElementService.GetByURI(ctx, uri)
}

// Elements is the resolver for the elements field.
func (r *queryResolver) Elements(ctx context.Context,
	limit *int32,
	after *string,
	typeURI *string,
	spaceURI *string,
	fieldValueFilter *model.FieldValueFilter) (
	*model.ElementConnection, error) {
	params := models.ListParams{
		After:            after,
		TypeURI:          typeURI,
		SpaceURI:         spaceURI,
		FieldValueFilter: fieldValueFilter,
	}
	if limit != nil {
		params.Limit = *limit
	}
	return r.ElementService.List(ctx, params)
}

// ElementUpdated is the resolver for the elementUpdated field.
func (r *subscriptionResolver) ElementUpdated(ctx context.Context, uri string) (<-chan *model.Element, error) {
	ch := r.ElementPubSub.Subscribe(uri)

	go func() {
		<-ctx.Done()
		r.ElementPubSub.Unsubscribe(uri, ch)
	}()

	return ch, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
