// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

type Element struct {
	URI          string               `json:"uri"`
	Title        string               `json:"title"`
	Type         *Type                `json:"type"`
	Space        *Space               `json:"space"`
	CreationDate string               `json:"creationDate"`
	Author       *User                `json:"author"`
	FieldValues  []*ElementFieldValue `json:"fieldValues"`
}

type ElementConnection struct {
	Edges      []*ElementEdge `json:"edges"`
	PageInfo   *PageInfo      `json:"pageInfo"`
	TotalCount int32          `json:"totalCount"`
}

type ElementEdge struct {
	Cursor string   `json:"cursor"`
	Node   *Element `json:"node"`
}

type ElementFieldValue struct {
	URI   string `json:"uri"`
	Value any    `json:"value"`
	Field *Field `json:"field"`
}

type Field struct {
	URI          string    `json:"uri"`
	Name         string    `json:"name"`
	FieldType    FieldType `json:"fieldType"`
	Type         *Type     `json:"type"`
	CreationDate string    `json:"creationDate"`
	Author       *User     `json:"author"`
	Options      *string   `json:"options,omitempty"`
	Required     bool      `json:"required"`
}

type FieldValueFilter struct {
	FieldURI string `json:"fieldUri"`
	Value    string `json:"value"`
}

type Mutation struct {
}

type PageInfo struct {
	HasNextPage     bool    `json:"hasNextPage"`
	HasPreviousPage bool    `json:"hasPreviousPage"`
	StartCursor     *string `json:"startCursor,omitempty"`
	EndCursor       *string `json:"endCursor,omitempty"`
}

type Query struct {
}

type Space struct {
	URI          string  `json:"uri"`
	Name         string  `json:"name"`
	Tenant       *Tenant `json:"tenant"`
	CreationDate string  `json:"creationDate"`
}

type Subscription struct {
}

type Tenant struct {
	URI          string       `json:"uri"`
	Name         string       `json:"name"`
	Status       TenantStatus `json:"status"`
	CreationDate string       `json:"creationDate"`
}

type Type struct {
	URI          string `json:"uri"`
	Name         string `json:"name"`
	Space        *Space `json:"space"`
	CreationDate string `json:"creationDate"`
	Author       *User  `json:"author"`
}

type UpdateElementTitleInput struct {
	URI   string `json:"uri"`
	Title string `json:"title"`
}

type User struct {
	URI         string `json:"uri"`
	Email       string `json:"email"`
	DisplayName string `json:"displayName"`
}

type FieldType string

const (
	FieldTypeText        FieldType = "TEXT"
	FieldTypeNumber      FieldType = "NUMBER"
	FieldTypeDate        FieldType = "DATE"
	FieldTypeBoolean     FieldType = "BOOLEAN"
	FieldTypeSelect      FieldType = "SELECT"
	FieldTypeMultiSelect FieldType = "MULTI_SELECT"
	FieldTypeURL         FieldType = "URL"
	FieldTypeEmail       FieldType = "EMAIL"
)

var AllFieldType = []FieldType{
	FieldTypeText,
	FieldTypeNumber,
	FieldTypeDate,
	FieldTypeBoolean,
	FieldTypeSelect,
	FieldTypeMultiSelect,
	FieldTypeURL,
	FieldTypeEmail,
}

func (e FieldType) IsValid() bool {
	switch e {
	case FieldTypeText, FieldTypeNumber, FieldTypeDate, FieldTypeBoolean, FieldTypeSelect, FieldTypeMultiSelect, FieldTypeURL, FieldTypeEmail:
		return true
	}
	return false
}

func (e FieldType) String() string {
	return string(e)
}

func (e *FieldType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = FieldType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid FieldType", str)
	}
	return nil
}

func (e FieldType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *FieldType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e FieldType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type TenantStatus string

const (
	TenantStatusActive   TenantStatus = "ACTIVE"
	TenantStatusInactive TenantStatus = "INACTIVE"
)

var AllTenantStatus = []TenantStatus{
	TenantStatusActive,
	TenantStatusInactive,
}

func (e TenantStatus) IsValid() bool {
	switch e {
	case TenantStatusActive, TenantStatusInactive:
		return true
	}
	return false
}

func (e TenantStatus) String() string {
	return string(e)
}

func (e *TenantStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TenantStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TenantStatus", str)
	}
	return nil
}

func (e TenantStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *TenantStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e TenantStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
